app:
  name: cobagopi
  port: ":4000"
  encryption:
    salt: 10
    jwt_secret: secretjwtkey

db:
  host: localhost
  port: 5432
  name: gopi
  user: root
  password: secret*098
  connection_pool: 
    max_idle_connection: 10
    max_open_connection: 30
    max_lifetime_connection: 60 #sec
    max_iddletime_connection: 60 #sec